### ISSUE TITLE
数字を順番に並び替えたい

### ISSUE THREAD

**Issue by nao0725** [E-dmm/nagano-cake#33]
【解決したい課題】
数字順に並び替えたい！！

【現状】（エラー内容）
管理側の会員一覧でid 順に並ばず困ってました。
ビューは表示はされてます！

【対策と自分の考え】
・コントローラーでASC,DESC使ったんですけどなかなか並び変わりませんでした
・他サイトでの確認（https://qiita.com/tsuchinoko_run/items/c31ed7e0b0672e6d898a）

上記試しましたが解消しませんでした。
ご確認をよろしくお願い致します。

【該当ソースコード】

````
Admin::CustomersController

 def index
    @customers = Customer.page(params[:page]).reverse_order.order(id:"ASC")
  end
````

````
admin/index.html.erb

  <table>
    <thead>
      <tr>
        <th>会員ID</th>
        <th>氏名</th>
        <th>メールアドレス</th>
        <th>ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= customer.last_name %> <%= customer.first_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.is_delete %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @customers %>

````

**Comment by shotaro0619** [comment]
def index
    @customers = Customer.all.order(created_at: :desc)
  end

はどうですか？

**Comment by shotaro0619** [comment]
ごめんなさい
def index
@customers = Customer.all.order(created_at: :asc)
end
かも

**Comment by nao0725** [comment]
上記の.order(created_at: :asc)で治りました！！！
作った順にすればよかったんですね、、、、、、！
