### ISSUE TITLE
【依頼】To ズッキーさん　管理者Homesコントローラー再作成

### ISSUE THREAD

**Issue by nao0725** [E-dmm/nagano-cake#34]
管理者のHomesコントローラー再作成お願い致します

【現状】
管理者のOrderコントローラーに一覧も入っている状態です。

【変更依頼箇所】
アプリケーション詳細設計３８行目のようにURLとコントローラーを変えて頂くようご確認をよろしくお願い致します。
https://docs.google.com/spreadsheets/d/15U4bh5fVehia3N_PlWLB6v6cH8_nd0nUuTGqBHFDY4I/edit#gid=1070651208

**Comment by zucky-quest** [comment]
完了しました。

**Comment by nao0725** [comment]
@kanbaru-github 
ありがとうございます！！
編集した文のプルリクって頂けました？？？
