### ISSUE TITLE
商品をカートに入れられません

### ISSUE THREAD

**Issue by zucky2021** [E-dmm/nagano-cake#36]
カートに商品を入れるとルーティングエラーが起こります。

<%= form_with model: @cart_products, url: 'cart_products_path', local:true do |f| %>
<% end %>

**Comment by nao0725** [comment]
@kanbaru-github 
urlのとこ間違いなのかなーと思いましたがroutesみたら一致してたので問題なさそうです。
タローさんわからなかったら質問しましょう！質問同席させてください！

**Comment by nao0725** [comment]
ちなみにコントローラーのりダイレクト先は関係ないですか？？？
