### ISSUE TITLE
退会するボタンを押してもログアウトされない　ログインできてしまう

### ISSUE THREAD

**Issue by shotaro0619** [E-dmm/nagano-cake#41]
public/customers_controller.rb
@customer = current_customer
    #is_deleteカラムにフラグを立てる(defaultはfalse)
    @customer.update(is_delete: true)
    #ログアウトさせる
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path

上記でupdateできていない？

models/customer.rb
  # def active_for_authentication?
  #   super && (self.is_delete == false)
  # end

上記を記述したいがコメントアウトを外すとログインできなくなってしまう
falseのところをtrueに変えると退会するを押した会員はログインできて退会していない会員はログインできなくなってしまう
フラグはtrueに変わっている？

**Comment by nao0725** [comment]
@shotaro0619 
これはwithdrawのアクションですか？？
そっちは見たところ問題なさそうです、、！
問題はモデルの方なんですけど、そっちはわからないですね、、、
参考サイトこれですか？？？
https://gist.github.com/mignonstyle/083c9e1651d7734f84c99b8cf49d57fa

**Comment by nao0725** [comment]
以下質問文です！

【解決したい課題】
①退会機能で退会したときにログアウトしたい！

【現状】（エラー内容）
①退会ボタンを押すとログアウトできない上に、退会ができてない状態

上記試しましたが解消しませんでした。
ご確認をよろしくお願い致します。

**Comment by nao0725** [comment]
質問の解答

【原因】
26行目のreset sessionが動いてない！！

【対策】
reset sessionの記述を消して、
いつも通りのログアウトで設定する！
application_controllerのafter_sign_outに飛ばす！
→リダイレクト先を変更
→新しくdeviseのスコープが必要なので下記を追加した
devise_scope :customer do
       get "/customers/logout" => "devise/sessions#destroy", as: :logout
end
と追加

参考サイト
https://31webcreation.hatenablog.com/entry/set-page-after-login-and-logout
